import { DropDownItem } from '../../shared/components/dropdown-selector/dropdown-selector';

export const DropdownItems: DropDownItem[] = [
  {
    id: '1',
    icon: 'dashboard',
    title: 'Dashboard',
    description: 'Overview of your account and activity',
    routeTo: '/dashboard',
    tags: ['/', 'dashboard', 'home'],
    category: 'Dashboard',
    // permissions:'dashboard:view'
  },
  {
    id:'1.5',
    icon: 'calendar_today',
    title: 'Attendance',
    description: 'Manage your attendance',
    category: 'Attendance Management',
    childItems: [
       {
        id:'1.5.1',
        icon: 'add',
        title: 'New Attendance Adjustment',
        description: 'Add an attendance adjustment',
        routeTo: '/attendance/adjustment/new',
        tags: ['new','adjustment','attendance','create'],
        category: 'Attendance Management',
        // permissions: 'attendance-adjustment:create',
      },
      
      {
        id:'1.5.2',
        icon: 'history',
        title: 'Attendance History',
        description: 'View your all attendance',
        routeTo: '/attendance/history',
        tags: ['all','history','attendance','view','date'],
        category: 'Attendance Management',
        // permissions: 'attendance-history:view',
      },
      {
        id:'1.5.3',
        icon: 'list',
        title: 'Attendance Adjustments',
        description: 'View all attendance adjustments',
        routeTo: '/attendance/adjustments-approval/all',
        tags: ['all','history','attendance','view','date'],
        category: 'Attendance Management',
        // permissions: 'admin-attendance-adjustment:view',
      },
    ],
  },
  {
    id: '2',
    icon: 'person_outline',
    title: 'Employee',
    category: 'Employee Management',
    description: 'Manage employee and roles',
    childItems: [
      {
        id: '2.1',
        icon: 'add',
        title: 'Add Employee',
        description: 'Add an employees',
        routeTo: '/employee/new',
        tags: ['hire', 'new', 'staff', 'add', 'create', 'onboard'],
        category: 'Employee Management',
        // permissions: 'employee:create',
      },
      {
        id: '2.2',
        icon: 'cloud_upload',
        title: 'Bulk Upload Employee',
        description: 'Bulk upload employee using CSV',
        routeTo: '/employee/new/bulk-upload',
        tags: ['bulk', 'upload', 'new', 'employee'],
        category: 'Employee Management',
        // permissions: 'employee:create',
      },
      {
        id: '2.3',
        icon: 'people_outline',
        title: 'All Employees',
        description: 'View all employees',
        routeTo: '/employee/all',
        tags: ['staff', 'list', 'profiles', 'members', 'find'],
        category: 'Employee Management',
        // permissions: 'employee:view',
      },
      {
        id: '2.4',
        icon: 'security',
        category: 'Employee Management',
        title: 'Roles',
        description: 'Manage user roles and permissions',
        childItems: [
          {
            id: '2.4.1',
            icon: 'supervised_user_circle',
            title: 'All Roles',
            description: 'View all Roles',
            routeTo: '/roles/all',
            category: 'Employee Management',
          },
        ],
      },
    ],
  },
    {
      id:'2',
      icon: 'beach_access',
      title: 'Leaves',
      description: 'Manage or create leaves request',
    category: 'Dashboard',
      childItems: [
         {
        id:'2.1',
        icon: 'add',
        title: 'New Leave Request',
        description: 'Create a leave request',
        routeTo: '/leave-requests/new',
        tags: ['new','leave','request','create','attendance'],
        category: 'Leave Management',
        // permissions: 'leaves:create',
      },
       {
        id:'2.2',
        icon: 'list',
        title: 'Your Leave Requests',
        description: 'View all your leave request',
        routeTo: '/leave-requests/my',
        tags: ['all','leave','request','view','attendance'],
        category: 'Leave Management',
        // permissions: 'leaves-requests:view',
      },
      {
        id:'2.2',
        icon: 'list',
        title: 'Employee Leave Requests',
        description: 'View all leave request for the employees',
        routeTo: '/leave-requests/all',
        tags: ['all','leave','request','view','attendance'],
        category: 'Leave Management',
        // permissions: 'admin-leave-requests:view',
      },
      ],
    },
  //   {
  //     icon: 'settings',
  //     title: 'Settings',
  //     description: 'Configure application preferences',
  //     childItems: [
  //       {
  //         icon: 'person',
  //         title: 'Profile',
  //         description: 'Update your profile information',
  //         routeTo: '/settings/profile',
  //       },
  //       {
  //         icon: 'security',
  //         title: 'Security',
  //         description: 'Manage password and authentication',
  //         routeTo: '/settings/security',
  //       },
  //       {
  //         icon: 'notifications',
  //         title: 'Notifications',
  //         description: 'Configure notification preferences',
  //         routeTo: '/settings/notifications',
  //       },
  //     ],
  //   },
  {
    id: '3',
    icon: 'help_outline',
    title: 'Help Center',
    description: 'Documentation and support resources',
    category: 'User Help',
    tags: ['help'],
    routeTo: '/help',
  },
];
