import { Employee } from "./employee.model";

/**
 * Mock dataset — a ~16-person company with a CEO at the top, two directors
 * reporting to her, and managers/ICs beneath them. Swap this out for your
 * real EmployeeService call once wired up.
 */
export const MOCK_EMPLOYEES: any[] = [
  {
    id: 'e-001',
    userId: 'u-001',
    staffNo: 'STF-001',
    firstName: 'Amina',
    lastName: 'Sheikh',
    fullName: 'Amina Sheikh',
    email: 'amina.sheikh@company.com',
    departmentName: 'Executive',
    branchName: 'Karachi HQ',
    jobTitleName: 'Chief Executive Officer',
    managerId: undefined,
    isActive: true,
    createdAtUtc: new Date('2019-01-10'),
    role: 'Admin',
    status: 'Active',
  },
  {
    id: 'e-002',
    userId: 'u-002',
    staffNo: 'STF-002',
    firstName: 'Bilal',
    lastName: 'Ahmed',
    fullName: 'Bilal Ahmed',
    email: 'bilal.ahmed@company.com',
    departmentName: 'Engineering',
    branchName: 'Karachi HQ',
    jobTitleName: 'Director of Engineering',
    managerId: 'e-001',
    managerName: 'Amina Sheikh',
    isActive: true,
    createdAtUtc: new Date('2019-03-15'),
    role: 'Admin',
    status: 'Active',
  },
  {
    id: 'e-003',
    userId: 'u-003',
    staffNo: 'STF-003',
    firstName: 'Sana',
    lastName: 'Raza',
    fullName: 'Sana Raza',
    email: 'sana.raza@company.com',
    departmentName: 'People & Culture',
    branchName: 'Karachi HQ',
    jobTitleName: 'Director of HR',
    managerId: 'e-001',
    managerName: 'Amina Sheikh',
    isActive: true,
    createdAtUtc: new Date('2019-05-01'),
    role: 'Admin',
    status: 'Active',
  },
  {
    id: 'e-004',
    userId: 'u-004',
    staffNo: 'STF-004',
    firstName: 'Usman',
    lastName: 'Khan',
    fullName: 'Usman Khan',
    email: 'usman.khan@company.com',
    departmentName: 'Engineering',
    branchName: 'Karachi HQ',
    jobTitleName: 'Engineering Manager, Backend',
    managerId: 'e-002',
    managerName: 'Bilal Ahmed',
    isActive: true,
    createdAtUtc: new Date('2020-02-11'),
    role: 'User',
    status: 'Active',
  },
  {
    id: 'e-005',
    userId: 'u-005',
    staffNo: 'STF-005',
    firstName: 'Hira',
    lastName: 'Malik',
    fullName: 'Hira Malik',
    email: 'hira.malik@company.com',
    departmentName: 'Engineering',
    branchName: 'Lahore Branch',
    jobTitleName: 'Engineering Manager, Frontend',
    managerId: 'e-002',
    managerName: 'Bilal Ahmed',
    isActive: true,
    createdAtUtc: new Date('2020-04-20'),
    role: 'User',
    status: 'Active',
  },
  {
    id: 'e-006',
    userId: 'u-006',
    staffNo: 'STF-006',
    firstName: 'Fahad',
    lastName: 'Iqbal',
    fullName: 'Fahad Iqbal',
    email: 'fahad.iqbal@company.com',
    departmentName: 'HR',
    branchName: 'Karachi HQ',
    jobTitleName: 'HR Business Partner',
    managerId: 'e-003',
    managerName: 'Sana Raza',
    isActive: true,
    createdAtUtc: new Date('2021-01-05'),
    role: 'User',
    status: 'Active',
  },
  {
    id: 'e-007',
    userId: 'u-007',
    staffNo: 'STF-007',
    firstName: 'Zara',
    lastName: 'Farooq',
    fullName: 'Zara Farooq',
    email: 'zara.farooq@company.com',
    departmentName: 'HR',
    branchName: 'Karachi HQ',
    jobTitleName: 'Talent Acquisition Lead',
    managerId: 'e-003',
    managerName: 'Sana Raza',
    isActive: true,
    createdAtUtc: new Date('2021-06-18'),
    role: 'User',
    status: 'Active',
  },
  {
    id: 'e-008',
    userId: 'u-008',
    staffNo: 'STF-008',
    firstName: 'Ali',
    lastName: 'Hassan',
    fullName: 'Ali Hassan',
    email: 'ali.hassan@company.com',
    departmentName: 'Engineering',
    branchName: 'Karachi HQ',
    jobTitleName: 'Senior Backend Engineer',
    managerId: 'e-004',
    managerName: 'Usman Khan',
    isActive: true,
    createdAtUtc: new Date('2021-09-01'),
    role: 'User',
    status: 'Active',
  },
  {
    id: 'e-009',
    userId: 'u-009',
    staffNo: 'STF-009',
    firstName: 'Mariam',
    lastName: 'Siddiqui',
    fullName: 'Mariam Siddiqui',
    email: 'mariam.siddiqui@company.com',
    departmentName: 'Engineering',
    branchName: 'Karachi HQ',
    jobTitleName: 'Backend Engineer',
    managerId: 'e-004',
    managerName: 'Usman Khan',
    isActive: true,
    createdAtUtc: new Date('2022-02-14'),
    role: 'User',
    status: 'Active',
  },
  {
    id: 'e-010',
    userId: 'u-010',
    staffNo: 'STF-010',
    firstName: 'Danish',
    lastName: 'Aziz',
    fullName: 'Danish Aziz',
    email: 'danish.aziz@company.com',
    departmentName: 'Engineering',
    branchName: 'Lahore Branch',
    jobTitleName: 'Backend Engineer',
    managerId: 'e-004',
    managerName: 'Usman Khan',
    isActive: true,
    createdAtUtc: new Date('2022-05-09'),
    role: 'User',
    status: 'Active',
  },
  {
    id: 'e-011',
    userId: 'u-011',
    staffNo: 'STF-011',
    firstName: 'Nida',
    lastName: 'Qureshi',
    fullName: 'Nida Qureshi',
    email: 'nida.qureshi@company.com',
    departmentName: 'Engineering',
    branchName: 'Lahore Branch',
    jobTitleName: 'Senior Frontend Engineer',
    managerId: 'e-005',
    managerName: 'Hira Malik',
    isActive: true,
    createdAtUtc: new Date('2021-11-22'),
    role: 'User',
    status: 'Active',
  },
  {
    id: 'e-012',
    userId: 'u-012',
    staffNo: 'STF-012',
    firstName: 'Omar',
    lastName: 'Baig',
    fullName: 'Omar Baig',
    email: 'omar.baig@company.com',
    departmentName: 'Engineering',
    branchName: 'Lahore Branch',
    jobTitleName: 'Frontend Engineer',
    managerId: 'e-005',
    managerName: 'Hira Malik',
    isActive: true,
    createdAtUtc: new Date('2022-08-30'),
    role: 'User',
    status: 'Active',
  },
  {
    id: 'e-013',
    userId: 'u-013',
    staffNo: 'STF-013',
    firstName: 'Sara',
    lastName: 'Yousuf',
    fullName: 'Sara Yousuf',
    email: 'sara.yousuf@company.com',
    departmentName: 'Engineering',
    branchName: 'Karachi HQ',
    jobTitleName: 'UI/UX Designer',
    managerId: 'e-005',
    managerName: 'Hira Malik',
    isActive: true,
    createdAtUtc: new Date('2023-01-16'),
    role: 'User',
    status: 'Active',
  },
  {
    id: 'e-014',
    userId: 'u-014',
    staffNo: 'STF-014',
    firstName: 'Kamran',
    lastName: 'Rafiq',
    fullName: 'Kamran Rafiq',
    email: 'kamran.rafiq@company.com',
    departmentName: 'Engineering',
    branchName: 'Karachi HQ',
    jobTitleName: 'QA Engineer',
    managerId: 'e-004',
    managerName: 'Usman Khan',
    isActive: true,
    createdAtUtc: new Date('2023-03-03'),
    role: 'User',
    status: 'Active',
  },
  {
    id: 'e-015',
    userId: 'u-015',
    staffNo: 'STF-015',
    firstName: 'Ayesha',
    lastName: 'Noor',
    fullName: 'Ayesha Noor',
    email: 'ayesha.noor@company.com',
    departmentName: 'HR',
    branchName: 'Lahore Branch',
    jobTitleName: 'HR Coordinator',
    managerId: 'e-007',
    managerName: 'Zara Farooq',
    isActive: true,
    createdAtUtc: new Date('2023-07-11'),
    role: 'User',
    status: 'Active',
  },
  {
    id: 'e-016',
    userId: 'u-016',
    staffNo: 'STF-016',
    firstName: 'Haris',
    lastName: 'Chaudhry',
    fullName: 'Haris Chaudhry',
    email: 'haris.chaudhry@company.com',
    departmentName: 'Engineering',
    branchName: 'Karachi HQ',
    jobTitleName: 'DevOps Engineer',
    managerId: 'e-002',
    managerName: 'Bilal Ahmed',
    isActive: true,
    createdAtUtc: new Date('2022-10-04'),
    role: 'User',
    status: 'Active',
  },
];